# Parameters for the Pioneer P3-DX robot

lookahead_distance: 0.25
max_linear_velocity: 0.1
max_rotational_velocity: 2.0
position_tolerance: 0.05
map_frame_id: map
# map_frame_id: robot_1/odom
robot_frame_id: robot_2/base_link
lookahead_frame_id: robot_2/lookahead

